### ISSUE TITLE
Piping functions specified with :: throws error

### ISSUE THREAD

**Issue by richierocks** [smbache/magrittr#78] opened 2015-04-20 08:33 UTC
To reproduce:

```{r}
data.frame(x = 1:10) %>% ncol
## [1] 1
data.frame(x = 1:10) %>% base::ncol
## Error in .::base : unused argument (ncol)
```

**Comment by smbache** [comment] 2015-04-20 10:26
This has been fixed in the github version, no?

**Comment by vincentarelbundock** [comment] 2015-06-01 17:38
I came here to file the same bug, and I can confirm that it seems fixed in the current github version. I tried the original example as well as the one that tripped me up personally:

    library(psych)
    library(magrittr)
    psych::describe(rnorm(100))
    rnorm(100) %>% psych::describe

**Closed** 2015-09-12 08:51 UTC

**Comment by ctbrown** [comment] 2016-12-07 18:18
It is unfortunate that the github and CRAN have the same version number (1.5); since they are clearly different.  To fix this issue you must install from github,:

> devtools::install_github("tidyverse/magrittr")

**Comment by LeeMendelowitz** [comment] 2018-01-18 21:39
Thanks for the help here. Installing from GitHub resolves the issue. This is still a problem in the CRAN version of magrittr in January 2018.

**Comment by MatthieuStigler** [comment] 2019-03-05 00:54
Seems this issue is tricking more than one person, see the issue on StackOverflow: https://stackoverflow.com/questions/54992188/r-using-pipe-and-pkgfo-leads-to-error-error-in-base-unused-argument/54992189?noredirect=1#comment96742243_54992189

**Comment by oganm** [comment] 2025-04-08 22:10
Not sure if anyone would be peeking here after all this time but I am curious, what just happened here? For the longest time the fix was exclusive to github, it appears to have since been removed from ther etoo
